# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mysql:5.7-ram

      
    steps:
        - checkout

        - run: sudo apt update
        - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
        - restore_cache:
              keys:
            # "composer.lock" can be used if it is committed to the repo
                - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

        - run: composer install --no-dev
        - run:
            name: Setup Laravel testing environment variables for CircleCI test
            command: cp .env .env
        - save_cache:
            key: v1-dependencies-{{ checksum "composer.json" }}
            paths:
                - ./vendor
        - restore_cache:
            keys:
                - node-v1-{{ checksum "composer.json" }}
                - node-v1-
        - run: yarn install
        - save_cache:
            key: node-v1-{{ checksum "composer.json" }}
            paths:
                - node_modules

      # prepare the database
        #- run: touch storage/testing.sqlite
        - run: php artisan dusk --group=register

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
        #- run: ./vendor/bin/codecept build
        #- run: ./vendor/bin/codecept run
